import Link from "next/link";

export const metadata = { title: "Terms of Service — PARALLEL" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-parallel-bg px-8 py-16 max-w-3xl mx-auto">
      <Link href="/" className="text-parallel-dim hover:text-parallel-text text-sm transition-colors">← Back</Link>
      <h1 className="font-display font-bold text-3xl text-parallel-text mt-8 mb-2">Terms of Service</h1>
      <p className="text-parallel-dim text-sm mb-10">Last updated: January 1, 2025</p>

      <div className="space-y-8 text-parallel-dim leading-relaxed text-sm">
        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using PARALLEL, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">2. Description of Service</h2>
          <p>PARALLEL is an AI-native identity exploration platform that allows users to create and interact with divergent AI representations of themselves called "Parallels." The service uses artificial intelligence to generate conversations and insights.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">3. Not a Mental Health Service</h2>
          <p>PARALLEL is not a mental health service, therapy, or crisis intervention service. The AI Parallels are not therapists, counselors, or mental health professionals. If you are experiencing a mental health crisis, please contact a qualified professional or emergency services immediately.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">4. User Responsibilities</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You agree not to use the service for any unlawful purpose or to harass, harm, or exploit others.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">5. AI-Generated Content</h2>
          <p>Content generated by your Parallels is produced by artificial intelligence and may not always be accurate, appropriate, or reflect actual outcomes of life choices. Do not make major life decisions based solely on AI-generated insights.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">6. Subscription and Billing</h2>
          <p>PARALLEL offers free and paid subscription tiers. Paid subscriptions are billed monthly or annually. You may cancel at any time; cancellation takes effect at the end of the current billing period.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">7. Termination</h2>
          <p>We reserve the right to terminate accounts that violate these terms. You may delete your account at any time from account settings.</p>
        </section>

        <section>
          <h2 className="text-parallel-text font-semibold text-lg mb-3">8. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:legal@parallel.app" className="text-parallel-accent hover:underline">legal@parallel.app</a>.</p>
        </section>
      </div>
    </div>
  );
}
